In [4]:
#Imports goes at top
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('/kaggle/input/datasets/ankushsonawane/insurance-claim/Insurance_Claim.csv')

In [6]:
df.head()

,age,gender,bmi,childern,smoker,region,charges,insuranceclaim
0,19.0,female,27.900,0,yes,southwest,16884.92400,yes
1,18.0,male,33.770,1,no,southeast,1725.55230,yes
2,28.0,male,33.000,3,no,southeast,4449.46200,no
3,33.0,male,22.705,0,no,northwest,21984.47061,no
4,32.0,male,28.880,0,no,northwest,3866.85520,yes

In [7]:
df.isnull().sum()

age                6
gender             0
bmi                5
childern           0
smoker             0
region             2
charges           12
insuranceclaim     0
dtype: int64

In [8]:
df['age'] = df['age'].ffill() # forward fill
df['bmi'] = df['bmi'].fillna(df['bmi'].mean()) # mean fill
df['region'] = df['region'].fillna(df['region'].mode()[0]) # mode fill for categorical
df['charges'] = df['charges'].fillna(df['charges'].mean()) # mean fill

In [9]:
#Lets convert the categorical variables into numerical variables
df['gender'] = df['gender'].astype('category').cat.codes
df['smoker'] = df['smoker'].astype('category').cat.codes
df = pd.get_dummies(df, columns=['region'], drop_first=True,dtype=np.int16) # one hot encoding for region
df['insuranceclaim'] = df['insuranceclaim'].astype('category').cat.codes

In [10]:
df.head()

,age,gender,bmi,childern,smoker,charges,insuranceclaim,region_northwest,region_southeast,region_southwest
0,19.0,0,27.900,0,1,16884.92400,1,0,0,1
1,18.0,1,33.770,1,0,1725.55230,1,0,1,0
2,28.0,1,33.000,3,0,4449.46200,0,0,1,0
3,33.0,1,22.705,0,0,21984.47061,0,1,0,0
4,32.0,1,28.880,0,0,3866.85520,1,1,0,0

In [11]:
training_data = df.drop(['gender','region_southwest'],axis=1)

In [12]:
x = training_data.drop('insuranceclaim',axis=1)
y = training_data['insuranceclaim']

In [13]:
# Make Imports At Top
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y)

In [15]:
logmodel = LogisticRegression(max_iter=1000)
logmodel.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [16]:
y_pred = logmodel.predict(x_test)

In [17]:
accuracy_score(y_test, y_pred)

0.8507462686567164

In [18]:
confusion_matrix(y_test, y_pred)

array([[ 89,  22],
       [ 18, 139]])